name: "HCL AppScan CodeSweep"
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish issues to ASoC
        uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v2
        with:
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          publish_on_merge: true
          application_id: 4b48b679-d53e-4253-aebb-49bef9d56716
    env: 
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
